@if(auth()->user()->role === 'superadmin')
    @include('layouts.sidebar.superadmin')
@elseif(auth()->user()->role === 'admin')
    @include('layouts.sidebar.admin')
@elseif(auth()->user()->role === 'finance')
    @include('layouts.sidebar.finance')
@elseif(auth()->user()->role === 'gudang')
    @include('layouts.sidebar.gudang')
@elseif(auth()->user()->role === 'direktur')
    @include('layouts.sidebar.direktur')
@endif
